# Generated by Django 3.1 on 2020-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200915_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=1000)),
                ('landmark', models.CharField(max_length=600)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField(default=0)),
            ],
        ),
    ]
